server.port=8081
spring.application.name=AAS Environment

basyx.backend=InMemory
basyx.environment=file:/application/aasx

basyx.cors.allowed-origins=http://localhost:8080,http://localhost:3000,http://localhost:5173
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
