operation-data:
  sources:
    - factory-code: MTK01
      area-code: F1
      line-code: NI1
      asset-type: REC
      table-name: platservice_1
      asset-code-column: assetCode
      type-index-column: plating_element_type_index
      value-column: plating_now_value
      metrics:
        - type-index: 3
          id-short: VLT
          unit: V
          value-type: xs:double
          sort-order: 1
        - type-index: 4
          id-short: CUR
          unit: A
          value-type: xs:double
          sort-order: 2
    - factory-code: MTK01
      area-code: F1
      line-code: NI2
      asset-type: REC
      table-name: platservice_2
      asset-code-column: assetCode
      type-index-column: plating_element_type_index
      value-column: plating_now_value
      metrics:
        - type-index: 3
          id-short: VLT
          unit: V
          value-type: xs:double
          sort-order: 1
        - type-index: 4
          id-short: CUR
          unit: A
          value-type: xs:double
          sort-order: 2
    - factory-code: MTK01
      area-code: F1
      line-code: CUSN
      asset-type: REC
      table-name: platservice_3
      asset-code-column: assetCode
      type-index-column: plating_element_type_index
      value-column: plating_now_value
      metrics:
        - type-index: 3
          id-short: VLT
          unit: V
          value-type: xs:double
          sort-order: 1
        - type-index: 4
          id-short: CUR
          unit: A
          value-type: xs:double
          sort-order: 2
    - factory-code: MTK01
      area-code: F1
      line-code: NISN
      asset-type: REC
      table-name: platservice_4
      asset-code-column: assetCode
      type-index-column: plating_element_type_index
      value-column: plating_now_value
      metrics:
        - type-index: 3
          id-short: VLT
          unit: V
          value-type: xs:double
          sort-order: 1
        - type-index: 4
          id-short: CUR
          unit: A
          value-type: xs:double
          sort-order: 2
